# Generated by Django 4.2 on 2025-08-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('age', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('language', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=3)),
                ('vehicle', models.JSONField()),
            ],
        ),
    ]
