# Generated by Django 4.2 on 2025-08-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vien',
            name='language',
            field=models.JSONField(),
        ),
    ]
